name: Test Build

on:
  push:
    branches-ignore: ["main"] 
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:

      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup python3
        uses: actions/setup-python@v5
        with:
          python-version: '3.13'

      - name: Test
        run: |
          python3 -m venv chelydra_testenv
          source chelydra_testenv/bin/activate
          pip3 install pytest build
          python3 -m build
          dir dist/*.whl | xargs -I {} pip install {}
          pytest
          deactivate