name: Publish rc

on:
  push: 
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:

      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup python3
        uses: actions/setup-python@v5
        with:
          python-version: '3.13'

      - name: Update version
        run: echo "$(cat version.txt).rc-$(date +%s)" > version.txt

      - name: Publish
        run: | 
          python3 -m venv chelydra_buildenv
          source chelydra_buildenv/bin/activate
          pip install twine pytest build
          python3 -m build
          dir dist/*.whl | xargs -I {} pip install {}
          pytest
          twine upload -u __token__ -p ${{ secrets.PYPI_UPLOAD_CHELYDRA_TWINE_TOKEN }} dist/*
          deactivate